Repository taskcluster/taskcluster, pull requests merged in 2019-02, with the labels that each got.

#178 [Bug 1524942] [UI] Add default sort to AWS provisioning recent errors
  ui/src/components/AwsProvisionerErrorsTable/index.jsx
Labels: ui

#154 Add configuration file for web-ui
  infrastructure/builder/docs/cluster-spec.md
  infrastructure/builder/src/build/monoimage.js
  infrastructure/builder/src/build/service.js
  infrastructure/builder/src/build/service/web-ui-dockerfile.dot
  infrastructure/builder/src/build/service/web-ui-nginx-site.conf
  infrastructure/builder/src/build/service/web-ui.js
  infrastructure/builder/taskcluster-spec/build.yml
  infrastructure/terraform/ingress.yaml
  infrastructure/terraform/taskcluster.tf.json
  infrastructure/terraform/tools-ui.tf
  infrastructure/terraform/web-ui.tf
Labels: ui

#187 Update web-ui-nginx-site.conf
  infrastructure/builder/src/build/service/web-ui-nginx-site.conf
Labels: ui

#198 Switch to Node 10.15.1
  .taskcluster.yml
  infrastructure/browser-test/README.md
  netlify.toml
  package.json
  ui/package.json
Labels: housekeeping, merge and deploy, renovate doesn't like our node

#197 Refactor 🤪
  services/login/src/handlers/mozilla-auth0.js
  services/login/test/handlers_mozilla_auth0_test.js
Labels: login

#194 Web server on kube
  infrastructure/builder/taskcluster-spec/build.yml
  infrastructure/terraform/ingress.yaml
  infrastructure/terraform/web-server-service.tf
  infrastructure/terraform/web-ui.tf
Labels: web-server

#215 Only post "No taskcluster jobs.." to a PR once part2 and part3
  services/github/src/handlers.js
Labels: github

#263 Reorganize and correct the flow in jobHandlers
  services/github/src/handlers.js
  services/github/src/intree.js
  services/github/src/pr-allowed.js
  services/github/test/data/yml/invalid-yaml.json
  services/github/test/data/yml/valid-yaml.json
  services/github/test/github-auth.js
  services/github/test/handler_test.js
  services/github/test/intree_test.js
  services/github/test/pr-allowed_test.js
Labels: github, merge and deploy

#308 Change terraform to deploy ui from the monoimage
  infrastructure/terraform/ingress.yaml
  infrastructure/terraform/modules/deployment/deployment.yaml
  infrastructure/terraform/taskcluster.tf.json
  infrastructure/terraform/web-ui.tf
Labels: ui

#302 [UI] Remove redundant sign-in chooser
  ui/src/components/SignInDialog/index.jsx
Labels: ui

#272 Upgrade octokit, tc-github auth stuff
  infrastructure/terraform/github-service.tf
  infrastructure/terraform/taskcluster.tf.json
  infrastructure/terraform/variables.tf
  services/github/app.json
  services/github/config.yml
  services/github/package.json
  services/github/src/github-auth.js
  services/github/src/main.js
  services/github/test/github-auth.js
  yarn.lock
Labels: github
