Repository taskcluster/taskcluster, pull requests merged in 2019-01, with the labels that each got.

#58 Bug 1518186 - include full URL in legacy published refs for events, too
  libraries/pulse/src/publisher.js
Labels: review

#57 Test for missing/extra packages
  libraries/app/package.json
  libraries/client/package.json
  libraries/docs/package.json
  libraries/references/package.json
  libraries/testing/package.json
  libraries/typed-env-config/package.json
  libraries/validate/package.json
  package.json
  services/auth/bin/load-test.js
  services/auth/package.json
  services/notify/package.json
  services/queue/package.json
  services/treeherder/package.json
  test/meta_test.js
  yarn.lock
Labels: review

#59 Switch to Node 10.14
  .taskcluster.yml
  infrastructure/builder/package.json
  services/auth/package.json
  services/github/package.json
  services/hooks/package.json
  services/index/package.json
  services/login/package.json
  services/notify/package.json
  services/purge-cache/package.json
  services/queue/package.json
  services/secrets/package.json
  services/treeherder/package.json
Labels: merge and deploy

#60 Switch to Auth0 library for correct runtime env
  services/login/package.json
  services/login/src/handlers/mozilla-auth0.js
  yarn.lock
Labels: merge and deploy

#70 Start using checks api for our .tc.yml tests
  .taskcluster.yml
Labels: review

#50 Use hasOwnProperty as it is faster and more sane
  libraries/scopes/src/expressions.js
Labels: merge and deploy

#72 Temporarily set libxmljs directly in remotely-signed-s3 to de-flake tests
  package.json
  yarn.lock
Labels: review

#76 Fix broken links in taskcluster building docs
  infrastructure/builder/docs/building-taskcluster.md
Labels: review

#73 Bug 1518896 - Fix container listing test
  services/auth/src/azure.js
  services/auth/test/azure_test.js
Labels: review

#83 Properly await table row removal in tests
  services/purge-cache/test/helper.js
Labels: merge and deploy, review

#33 Bug 1516463 - use minItems, not minLength, for array length
  services/queue/schemas/v1/post-artifact-request.yml
Labels: merge and deploy

#86 Bug 1520061 - build monorepo from a git clone, not working copy
  infrastructure/builder/src/build/repo.js
  infrastructure/builder/taskcluster-spec/build.yml
Labels: review

#85 Bug 1417662: fix flaky purge-cache tests
  services/purge-cache/test/helper.js
Labels: review

#78 Add some tc-gh goodness to README
  README.md
Labels: enhancement, review

#77 Have a better task info in Checks
  services/github/src/handlers.js
  services/github/test/handler_test.js
Labels: enhancement, github service, merge and deploy

#97 Add web-server to monorepo: Fix linting
  package.json
  services/web-server/.neutrinorc.js
  services/web-server/Procfile
  services/web-server/package.json
  services/web-server/src/PulseEngine/index.js
  services/web-server/src/graphql/Tasks.graphql
  services/web-server/src/resolvers/Tasks.js
  services/web-server/src/servers/createApp.js
  yarn.lock
Labels: web-server

#98 Bug 1260285 - publish legacy schemas with a rewritten $schema
  libraries/validate/src/schemaset.js
Labels: lib-validate

#111 Remove stray curly bracket
  services/github/src/handlers.js
Labels: bug, github

#118 Bug in checks: creates a checkrun for the whole group
  services/github/src/handlers.js
  services/github/src/tc-yaml.js
Labels: bug, github, merge and deploy

#122 Revert "Expire queues after 4 days of not being used"
  libraries/pulse/README.md
  libraries/pulse/src/consumer.js
Labels: bug, lib-pulse

#125 Bug 1426512 - update all hawks to ^7.0.10
  libraries/api/package.json
  libraries/api/test/auth_test.js
  libraries/client/package.json
  libraries/client/src/client.js
  libraries/testing/package.json
  libraries/testing/test/fakeauth_test.js
  package.json
  services/auth/package.json
  services/auth/src/signaturevalidator.js
  services/auth/test/signaturevalidator_test.js
  services/references/src/main.js
  yarn.lock
Labels: merge and deploy

#116 Bug 1519870 - drop Hoek dependency
  services/auth/package.json
  services/auth/src/signaturevalidator.js
  services/auth/test/signaturevalidator_test.js
  yarn.lock
Labels: merge and deploy

#157 [Bug 1491551] continue - expire limit lastfires to 100 per hookId
  services/hooks/config.yml
  services/hooks/src/data.js
  services/hooks/src/main.js
  services/hooks/src/v1.js
  services/hooks/test/api_test.js
  services/hooks/test/expires_test.js
Labels: merge and deploy
