Repository taskcluster/taskcluster, pull requests merged in 2019-04, with the labels that each got.

#529 Change linting rules for switches
  .eslintrc.yml
  clients/client-web/src/WebListener.js
  services/auth/src/api.js
  services/github/src/api.js
  services/login/test/handlers_mozilla_auth0_test.js
  services/notify/src/handler.js
  services/queue/src/artifacts.js
  services/treeherder/src/handler.js
  services/treeherder/src/util/route_parser.js
  services/web-server/src/resolvers/Tasks.js
  services/worker-manager/bin/convert.js
Labels: merge and deploy

#528 Add GCP provider object. Implement listWorkers method
  services/worker-manager/package.json
  services/worker-manager/src/main.js
  services/worker-manager/src/providers/gcpprovider.js
  services/worker-manager/src/worker.js
Labels: :baby_chick: worker-manager :baby_chick:

#542 Remove leftovers of tc-client.PulseListener
  clients/client/README.md
  libraries/monitor/README.md
  libraries/testing/README.md
  libraries/testing/src/pulse.js
  libraries/testing/src/testing.js
Labels: merge and deploy

#544 Bug 1540160 - add bash to the built image
  infrastructure/builder/README.md
  infrastructure/builder/src/build/monoimage.js
Labels: merge and deploy

#527 Bug 1535316 - remove use of http-proxy for testing auth
  clients/client/test/retry_test.js
  package.json
  services/auth/src/main.js
  services/auth/test/helper.js
  yarn.lock
Labels: merge and deploy

#524 Bug 1540697 - improve idempotency of task creation, especially in hooks
  services/hooks/src/taskcreator.js
  services/hooks/test/scheduler_test.js
  services/hooks/test/taskcreator_test.js
  services/queue/test/createtask_test.js
Labels: merge and deploy

#537 use tdd for tc-web-server tests
  services/web-server/test/fetch_test.js
  services/web-server/test/mocha.opts
  services/web-server/test/pulseengine_test.js
Labels: merge and deploy

#526 Bug 1534713 - better debugging for pulse issues
  libraries/monitor/src/index.js
  libraries/monitor/test/base_test.js
  libraries/monitor/test/exit.js
  libraries/pulse/test/client_test.js
  libraries/pulse/test/consumer_test.js
  libraries/pulse/test/publisher_test.js
Labels: merge and deploy

#541 Bug 1525030 - move all dependencies to the top level
  libraries/api/package.json
  libraries/app/package.json
  libraries/azure/package.json
  libraries/config/package.json
  libraries/docs/package.json
  libraries/iterate/package.json
  libraries/loader/package.json
  libraries/monitor/package.json
  libraries/pulse/package.json
  libraries/references/package.json
  libraries/scopes/package.json
  libraries/testing/package.json
  libraries/validate/package.json
  package.json
  services/auth/package.json
  services/github/package.json
  services/hooks/package.json
  services/index/package.json
  services/login/package.json
  services/notify/package.json
  services/purge-cache/package.json
  services/queue/package.json
  services/secrets/package.json
  services/treeherder/package.json
  services/web-server/package.json
  services/worker-manager/package.json
  test/meta_test.js
  yarn.lock
Labels: work-in-progress

#568 [UI] Fix calendar icon positioning on date picker
  ui/src/components/DatePicker/index.jsx
Labels: ui

#580 Worker Manager
  .gitignore
  clients/client-web/src/clients/WorkerManager.js
  clients/client/src/apis.js
  generated/references.json
  package.json
  services/worker-manager/Procfile
  services/worker-manager/bin/convert.js
  services/worker-manager/config.yml
  services/worker-manager/package.json
  services/worker-manager/procs.yml
  services/worker-manager/schemas/v1/anything.yml
  services/worker-manager/schemas/v1/create-workertype-request.yml
  services/worker-manager/schemas/v1/ruleset.yml
  services/worker-manager/schemas/v1/satisfiers.yml
  services/worker-manager/schemas/v1/test-worker-configuration.yml
  services/worker-manager/schemas/v1/worker-configuration.yml
  services/worker-manager/schemas/v1/workertype-full.yml
  services/worker-manager/src/api.js
  services/worker-manager/src/base.js
  services/worker-manager/src/bid.js
  services/worker-manager/src/bidding-strategies/queuepending.js
  services/worker-manager/src/bidding-strategy.js
  services/worker-manager/src/data-storage.js
  services/worker-manager/src/data.js
  services/worker-manager/src/main.js
  services/worker-manager/src/monitor.js
  services/worker-manager/src/provider.js
  services/worker-manager/src/provider_google.js
  services/worker-manager/src/provider_static.js
  services/worker-manager/src/provider_testing.js
  services/worker-manager/src/providers/gcpprovider.js
  services/worker-manager/src/provisioner.js
  services/worker-manager/src/rules.js
  services/worker-manager/src/shims.js
  services/worker-manager/src/worker-config.js
  services/worker-manager/src/worker.js
  services/worker-manager/test/api_test.js
  services/worker-manager/test/bid_test.js
  services/worker-manager/test/bidding-strategies/bidding-strategies_test.js
  services/worker-manager/test/bidding-strategies/queuepending_test.js
  services/worker-manager/test/convert-eval-expected.json
  services/worker-manager/test/convert-expected.json
  services/worker-manager/test/convert-input.json
  services/worker-manager/test/convert_test.js
  services/worker-manager/test/data-storage_test.js
  services/worker-manager/test/errors_test.js
  services/worker-manager/test/helper.js
  services/worker-manager/test/object_test.js
  services/worker-manager/test/providers/provider_test.js
  services/worker-manager/test/provisioner-example-worker-configuration.json
  services/worker-manager/test/provisioner_test.js
  services/worker-manager/test/rules_test.js
  services/worker-manager/test/worker-config_test.js
  yarn.lock
Labels: :baby_chick: worker-manager :baby_chick:

#617 Bug 1526705 - await workerinfo updates
  services/queue/src/workerinfo.js
  services/queue/test/workerinfo_test.js
Labels: flake-fix

#633 Add note on continuation token to best practices
  dev-docs/best-practices/microservices.md
Labels: docs

#566 Add main view (with some mock data)
  services/web-server/src/graphql/WorkerManager.graphql
  services/web-server/src/loaders/WorkerManager.js
  services/web-server/src/resolvers/WorkerManager.js
  ui/.neutrinorc.js
  ui/src/App/routes.jsx
  ui/src/components/Dashboard/SidebarList.jsx
  ui/src/components/DataTable/index.jsx
  ui/src/components/WorkerManagerWorkerTypesTable/index.jsx
  ui/src/utils/prop-types.js
  ui/src/views/WorkerManager/WorkerManagerViewWorkerTypes/WorkerManagerWorkerTypes.graphql
  ui/src/views/WorkerManager/WorkerManagerViewWorkerTypes/index.jsx
  ui/src/views/WorkerManager/WorkerManagerViewWorkers/WorkerManagerWorkers.graphql
  ui/src/views/WorkerManager/WorkerManagerViewWorkers/index.jsx
  ui/src/views/WorkerManager/index.jsx
  ui/src/views/WorkerManager/routes.js
Labels: :baby_chick: worker-manager :baby_chick:

#632 Add `list worker types` endpoint to worker manager
  clients/client-web/src/clients/WorkerManager.js
  clients/client/src/apis.js
  generated/references.json
  services/worker-manager/schemas/v1/workertype-list.yml
  services/worker-manager/src/api.js
Labels: :baby_chick: worker-manager :baby_chick:
