Repository taskcluster/taskcluster, pull requests merged in 2019-03, with the labels that each got.

#335 DB migration: add a table
  services/github/config.yml
  services/github/src/data.js
  services/github/src/handlers.js
  services/github/src/main.js
  services/github/test/helper.js
Labels: github

#356 Add Check-related Azure scopes to the terraform for Kube deployments
  infrastructure/terraform/auth-service.tf
Labels: github

#199 Bug 1515673 - YML changed for v1 in QuickStart
  ui/src/views/Quickstart/index.jsx
Labels: ui

#389 Bug 1523801 : Blacklist listening to some specific exchanges
  services/hooks/src/v1.js
Labels: merge and deploy

#403 Fix auth with entities
  libraries/testing/src/with-entity.js
  services/auth/test/helper.js
Labels: merge and deploy

#401 Bug 1534711 - pass rootUrl when initializing tc-client
  services/login/src/scanner.js
Labels: merge and deploy

#429 Scanner calls a function that is gone
  services/login/src/scanner.js
Labels: login

#430 Retry 404 and higher errors
  services/github/src/github-auth.js
Labels: github

#172 Bug 1524187 - Internal Server Errors when calling queue.completeArtifact
  services/queue/src/artifacts.js
Labels: merge and deploy

#452 Add gitversion to root as well
  libraries/monitor/src/index.js
Labels: merge and deploy

#436 Simplify lib-config
  infrastructure/builder/src/build/index.js
  libraries/config/README.md
  libraries/config/src/config.js
  libraries/config/src/schema.js
  libraries/config/test/config_test.js
  libraries/config/test/test-env.yml
  services/login/config.yml
  services/queue/config.yml
Labels: merge and deploy

#451 Fix my wrong review
  services/github/src/github-auth.js
Labels: merge and deploy

#417 [Bug 1535125] Part 1: Update critical part of lib-api and auth/queue
  generated/references.json
  libraries/api/src/api.js
  libraries/api/src/middleware/auth.js
  libraries/api/src/middleware/express-error.js
  libraries/api/src/middleware/handle.js
  libraries/api/src/middleware/schema.js
  libraries/api/test/responsetimer_test.js
  libraries/monitor/README.md
  libraries/monitor/src/builtins.js
  libraries/monitor/src/index.js
  libraries/monitor/src/logger.js
  libraries/monitor/src/monitor.js
  libraries/monitor/test/base_test.js
  services/auth/src/monitor.js
  services/auth/src/scoperesolver.js
  services/auth/src/signaturevalidator.js
  services/auth/test/scoperesolver_test.js
  services/auth/test/signaturevalidator_test.js
  services/queue/src/api.js
  services/queue/src/bucket.js
  services/queue/src/claimresolver.js
  services/queue/src/deadlineresolver.js
  services/queue/src/dependencyresolver.js
  services/queue/src/monitor.js
  services/queue/src/workclaimer.js
  ui/docs/generated/auth/references/logs.json
  ui/docs/generated/built-in-workers/references/logs.json
  ui/docs/generated/github/references/logs.json
  ui/docs/generated/hooks/references/logs.json
  ui/docs/generated/index/references/logs.json
  ui/docs/generated/login/references/logs.json
  ui/docs/generated/notify/references/logs.json
  ui/docs/generated/purge-cache/references/logs.json
  ui/docs/generated/queue/references/logs.json
  ui/docs/generated/references.json
  ui/docs/generated/secrets/references/logs.json
  ui/docs/generated/treeherder/references/logs.json
  ui/docs/generated/worker-manager/references/logs.json
  ui/src/views/Documentation/Reference/index.jsx
Labels: merge and deploy
